apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-u21h
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0019-tenant/tkrw-pr712-0075-0019-app/devfile-sample-u21h@sha256:3bb20b0f8f0df814777b65ad4a248092f2c256c415c8832ca0c548d40b6dcaa2
        name: my-nodejs
        resources: {}
status: {}
